name: Verify-beta
version: 1.0.1
api: 5.0.0
main: xDqZtop\verify\Main
author: xDqZtop
description: a Simple Verify Plugin.

commands:
  verify:
    permission: verify.command
permissions:
  verify.command:
    default: op
